_target_: ns_index.run_pipeline.compute_ns_roc
name: "neutral_space_idx"
area: "pfc"
output_path: ${pipelines.name}/${now:%Y_%m_%d_%H_%M_%S}/${pipelines.area}/

paths:
  input: "${workspace.data_path}/population/in_out_b1_b2/2025_01_03_12_05_07/${pipelines.area}/population.h5"
preprocessing:
  start_sample: 0
  end_sample: 400
  st_target: 0
  end_target: 400
  st_bl: -100
  end_bl: 0
  percentile: True
  cerotr: True