_target_: decoder.compute_decoding.run_decoding
name: "decoding"
area: "lip"
output_path: ${pipelines.name}/${pipelines.preprocessing.to_decode}/${pipelines.area}/${now:%Y_%m_%d_%H_%M_%S}

paths:
  input: "C:/Users/camil/Documents/int/code/Users/losadac/decoder/test.h5"
preprocessing:
  to_decode: "sampleid"
  min_ntr: 25
  start_sample: -200
  end_sample: 850
  start_test: -400
  end_test: 450
  step: 10
  time_before_son: "time_before_son_in"
  time_before_t1on: "time_before_t1on_in"
  sp_son: "sp_son_in"
  sp_t1on: "sp_t1on_in"
  mask_son: "mask_son_in"
  no_match: False
  avgwin: 100
decoder:
  niterations: 10
  ntr_train: 30
  ntr_test: 10
  svc_c: 0.8

