_target_: decoder.__main__.main
name: "decoding"
area: "lip"
output_path: ${pipelines.name}/${pipelines.preprocessing.to_decode}/${pipelines.area}/${now:%Y_%m_%d_%H_%M_%S}

paths:
  input: "C:/Users/camil/Documents/int/code/Users/population/lip/2024_08_28_11_46_33/population.h5"
preprocessing:
  to_decode: "sampleid"
  min_ntr: 25
  start_sample: -200
  end_sample: 850
  start_test: -400
  end_test: 450
  step: 10
  time_before_son: ${multiruns.time_before_son}
  time_before_t1on: ${multiruns.time_before_t1on}
  sp_son: ${multiruns.sp_son}
  sp_t1on: ${multiruns.sp_t1on}
  mask_son: ${multiruns.mask_son}
  no_match: False
  avgwin: 100
decoder:
  niterations: 10
  ntr_train: 30
  ntr_test: 10
  svc_c: 0.8

