_target_: decoder.__main__.main
name: "decoding"
area: "lip"
output_path: ${pipelines.name}/percentile_with_nonzero/300_cells/${now:%Y_%m_%d_%H_%M_%S}/${multiruns.name}/${pipelines.preprocessing.to_decode}/${pipelines.area}/${pipelines.decoder.svc_c}

paths:
  input: "${workspace.data_path}/population/${pipelines.area}/2024_08_28_12_23_36/population.h5"
preprocessing:
  to_decode: "orient"
  min_ntr: 25
  start_sample: -200
  end_sample: 850
  start_test: -400
  end_test: 500
  step: 10
  time_before_son: ${multiruns.time_before_son}
  time_before_t1on: ${multiruns.time_before_t1on}
  sp_son: ${multiruns.sp_son}
  sp_t1on: ${multiruns.sp_t1on}
  mask_son: ${multiruns.mask_son}
  no_match: False
  avgwin: 100
  zscore: True
  percentile: True
  cerotr: True
decoder:
  niterations: 1000
  ntr_train: 30
  ntr_test: 10
  svc_c: 0.001
  n_neurons: 300