_target_: population_distance.__main__.main
name: "population_distance"
area: "lip"
output_path: ${pipelines.name}/${pipelines.preprocessing.metric}/percentile_with_nonzero/all_neurons/${now:%Y_%m_%d_%H_%M_%S}/${multiruns.name}/${pipelines.area}

paths:
  input: "${workspace.data_path}/population/${pipelines.area}/2024_08_28_12_23_36/population.h5"
  nidpath: 
  # "${workspace.data_path}/selectivity/all_trials/2024_09_13_11_38_12/${pipelines.area}_no_neutral_inout_selectivity.csv"
  # "${workspace.data_path}/selectivity/percentile_with_nonzero/2024_09_23_17_09_29/${pipelines.area}_no_neutral_inout_selectivity.csv"
preprocessing:
  time_before_son: ${multiruns.time_before_son}
  time_before_t1on: ${multiruns.time_before_t1on}
  sp_son: ${multiruns.sp_son}
  sp_t1on: ${multiruns.sp_t1on}
  mask_son: ${multiruns.mask_son}
  start_sample : -200
  end_sample : 850
  start_test : -400
  end_test : 550
  n_test : 1
  min_trials : 25
  nonmatch: True
  avgwin : 100
  min_sp_sec : 1
  norm : False
  zscore : True
  select_n_neu : 100
  cerotr: True
  percentile: True
  metric: 'cosine'