_target_: plot_trials.run_pipeline.plot_trials
name: "plot_trials"
area: "lip"
output_path: ${pipelines.name}/percentile_with_nonzero/${now:%Y_%m_%d_%H_%M_%S}/b${pipelines.params.b}/${pipelines.area}/

paths:
  input: "${workspace.data_path}/new_structure/session_struct/${pipelines.area}/neurons/*neu.h5"
params:
  format: 'png'
  percentile: True
  cerotr: True
  b: 1
  hydra: True
