_target_: plot_trials.__main__.main
name: "plot_trials"
area: "lip"
output_path: ${pipelines.name}/all_trials/${now:%Y_%m_%d_%H_%M_%S}/b${b}/${pipelines.area}/

paths:
  input: "${workspace.data_path}/new_structure/session_struct/${pipelines.area}/neurons/*neu.h5"
params:
  format: 'png'
  percentile: False
  cerotr: False
  b: 1
