defaults:
  - workspace: niolon # vpn_local # 
  - pipelines: compute_receptive_field_b2
  #- multiruns: in
  #- override hydra/job_logging: disabled
  # - _self_
hydra:
  job:
    chdir: True # change dir before calling function
  run:
    dir: ${workspace.output_path}/${pipelines.output_path}
  sweep:
    dir: ${workspace.output_path}/${pipelines.output_path}
    subdir: .