defaults:
  - workspace: niolon
  - pipelines: compute_decoding
  - multiruns: decoding_contra
  - override hydra/job_logging: disabled
  - _self_
hydra:
  job:
    chdir: True # change dir before calling function
  run:
    dir: ${workspace.output_path}/${pipelines.output_path}
  sweep:
    dir: ${workspace.output_path}/${pipelines.output_path}
    subdir: .